/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (51.38%)
 * Total Accepted:    104.4K
 * Total Submissions: 203.2K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
    public char findTheDifference(String s, String t) {
        // int[] m = new int[26];
        // for(int i=0; i<s.length(); i++){
        //     m[s.charAt(i)-'a']++;
        // }
        // for(int i=0; i<t.length(); i++){
        //     if(m[t.charAt(i)-'a']==0) return t.charAt(i);
        //     else m[t.charAt(i)-'a']--;
        // }
        // return ' ';
        
        
        //tt has 1 more character than s
        int length = t.length()-1;
        char c = t.charAt(length);
        for(int i=0; i<length; i++){
            c^=s.charAt(i);
            c^=t.charAt(i);
        }
        return c;
    }
}
